from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Placeholder for the first migration. Create initial tables here.
    # Example:
    # op.create_table('analytics_data',
    #     sa.Column('id', sa.Integer(), nullable=False),
    #     sa.Column('metric_name', sa.String(), nullable=False),
    #     sa.Column('value', sa.Float(), nullable=False),
    #     sa.Column('timestamp', sa.DateTime(), nullable=False),
    #     sa.Column('company_id', sa.Integer(), nullable=True),
    #     sa.PrimaryKeyConstraint('id')
    # )
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Example:
    # op.drop_table('analytics_data')
    pass
    # ### end Alembic commands ### 